#
#
#

version: '3'
services:
  julia_0.5.0:
    image: julia:0.5.0
    container_name: julia_0.5.0
    volumes:
      - ./:/work
    working_dir: /work
    command: /bin/bash -c "julia src.jl < inp.txt"

  julia_0.5.1:
    image: julia:0.5.1
    container_name: julia_0.5.1
    volumes:
      - ./:/work
    working_dir: /work
    command: /bin/bash -c "julia src.jl < inp.txt"

  julia_1.0.5:
    image: julia:1.0.5
    container_name: julia_1.0.5
    volumes:
      - ./:/work
    working_dir: /work
    command: /bin/bash -c "julia src.jl < inp.txt"

  julia_1.2.0:
    image: julia:1.2.0
    container_name: julia_1.2.0
    volumes:
      - ./:/work
    working_dir: /work
    command: /bin/bash -c "julia src.jl < inp.txt"
